language: python
python:
  - "2.7"

install:
  - pip install -r dev-requirements.txt
  - pip install celery==$CELERY_VERSION

services:
  - redis-server

env:
  - CELERY_VERSION=3.1.0
  - CELERY_VERSION=3.1.1
  - CELERY_VERSION=3.1.2
  - CELERY_VERSION=3.1.3
  - CELERY_VERSION=3.1.4
  - CELERY_VERSION=3.1.5
  - CELERY_VERSION=3.1.6
  - CELERY_VERSION=3.1.7
  - CELERY_VERSION=3.1.8
  - CELERY_VERSION=3.1.9
  - CELERY_VERSION=3.1.10
  - CELERY_VERSION=3.1.11
  - CELERY_VERSION=3.1.12
  - CELERY_VERSION=3.1.13
  - CELERY_VERSION=3.1.14
  - CELERY_VERSION=3.1.15
  - CELERY_VERSION=3.1.16
  - CELERY_VERSION=3.1.17
  - CELERY_VERSION=3.1.18

script:
    - celery worker -l debug --config tests.settings -c 4 &> celery.log &
    - py.test
