language: python
python:
  - "2.7"

install: "pip install -r dev-requirements.txt"

services:
  - redis-server

env:
  - CELERYD_CONCURRENCY=1
  - CELERYD_CONCURRENCY=2
  - CELERYD_CONCURRENCY=4

script:
    - celery worker -l debug --config tests.settings -c $CELERYD_CONCURRENCY &> celery.log &
    - py.test
