language: python
python:
  - "2.7"

install: "pip install -r dev-requirements.txt"

services:
  - redis-server

script:
    - celery worker -l debug --config tests.settings &> celery.log &
    - py.test
